Make docker-admin smarter about mounting things in /opt/opencrowbar.
This should help Derek out a little bit.

diff --git a/tools/docker-admin b/tools/docker-admin
--- a/tools/docker-admin
+++ b/tools/docker-admin
@@ -36,9 +36,22 @@ if [[ ! $container = lxc ]]; then
         exit 1
     fi
 
+    if [[ $0 = /* ]]; then
+        mountdir="$0"
+    elif [[ $0 = .*  || $0 = */* ]]; then
+        mountdir="$(readlink -f "$PWD/$0")"
+    else
+        echo "Cannot figure out where core is!"
+        exit 1
+    fi
+    # This gets us to core
+    mountdir="${mountdir%/tools/docker-admin}"
+    # This gets us to the parent directory of core, where presumably the rest of our repos are checked out
+    mountdir="${mountdir%/*}"
+    echo "We will mount $mountdir at /opt/opencrowbar"
     mkdir -p "$HOME/.cache/opencrowbar/tftpboot"
-    
-    docker_args=(-t -i -w /opt/opencrowbar/core -v "$PWD:/opt/opencrowbar/core")
+
+    docker_args=(-t -i -w /opt/opencrowbar/core -v "$mountdir:/opt/opencrowbar")
     docker_args+=(-v "$HOME/.cache/opencrowbar/tftpboot:$tftproot")
     docker_args+=(-e "OUTER_UID=$(id -u)")
     docker_args+=(-e "OUTER_GID=$(id -g)")
